#! /usr/bin/env bash

# This script returns 0 if the value meets the wanted version.
# see http://masterminds.github.io/sprig/semver.html
#
# Example:
#    semver ">=1.2.0" "1.2.2" && echo ok || echo too bad

wanted="$1" value="$2" && shift 2

cat <<'EOF' | /usr/local/bin/gotemplate -PI -Vwanted="${wanted}" -Vvalue="${value}" $*
@-exit(iif(semverCompare(string(.wanted), string(.value)), 0, 1))
EOF
