# Build customization
builds:
  - binary: tgf
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

# Archive customization
archives:
  - format: zip

    replacements:
      amd64: 64-bits
      darwin: macOS

    files:
      - nothing.*

# GitHub release customization
release:
  draft: true
  prerelease: true
