name: Release on Tag
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # goreleaser needs the whole history to build the release notes

      - uses: goreleaser/goreleaser-action@9937f9bad91e089c6c6fe1d43dfa7b896ad6da21
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CGO_ENABLED: 0
