name: Release on Tag
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.17
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # goreleaser needs the whole history to build the release notes

      - uses: goreleaser/goreleaser-action@b508e2e3ef3b19d4e4146d4f8fb3ba9db644a757
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CGO_ENABLED: 0
