name: Release on Tag
on:
  push:
    tags:
      - "v*"
permissions:
  contents: read

jobs:
  release:
    permissions:
      contents: write  # for goreleaser/goreleaser-action to create a GitHub release
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # goreleaser needs the whole history to build the release notes

      - uses: goreleaser/goreleaser-action@7ec5c2b0c6cdda6e8bbb49444bc797dd33d74dd8
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CGO_ENABLED: 0
