name: Build
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
        id: go

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # goreleaser needs the whole history to build the release notes

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CGO_ENABLED: 0
