name: Test Install

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  posix:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - run: ./get-latest-tgf.sh

  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - run: ./get-latest-tgf.ps1
