name: Test Install

on:
  pull_request:
    branches:
      - main

jobs:
  posix:
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - run: ./get-latest-tgf.sh


  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - run: ./get-latest-tgf.ps1


  action:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          ref: ${{ github.head_ref }}

      - run: tgf --help-tgf
